name: Build & Push Base Rust ARMv7 Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  yew_builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run Docker on tmpfs
        uses: JonasAlfredsson/docker-on-tmpfs@v1
        with:
          tmpfs_size: 5
          swap_size: 4
      - name: Build for armv7 and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.arm
          platforms: linux/arm/v7
          push: true
          tags: stappsworldreport/yew_builder:arm-linux-gnueabihf
